/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IRatioController,
  IRatioControllerInterface,
} from "../IRatioController";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "totalDepositUSD",
        type: "uint256",
      },
    ],
    name: "getDepositSplit",
    outputs: [
      {
        internalType: "uint256",
        name: "wethAmountUSD",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "baseAmountUSD",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getTargetRatio",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "currentRatio",
        type: "uint256",
      },
    ],
    name: "isBalanced",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IRatioController__factory {
  static readonly abi = _abi;
  static createInterface(): IRatioControllerInterface {
    return new Interface(_abi) as IRatioControllerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IRatioController {
    return new Contract(address, _abi, runner) as unknown as IRatioController;
  }
}
