/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface ERC4626AprProviderInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MIN_SNAPSHOT_INTERVAL"
      | "acceptOwnership"
      | "fetchLiveApr"
      | "fetchStrategyApr"
      | "i_vault"
      | "owner"
      | "pendingOwner"
      | "renounceOwnership"
      | "s_keepers"
      | "s_latestSnapshot"
      | "s_prevSnapshot"
      | "setKeeper"
      | "snapshot"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "KeeperUpdated"
      | "OwnershipTransferStarted"
      | "OwnershipTransferred"
      | "SnapshotRecorded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MIN_SNAPSHOT_INTERVAL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fetchLiveApr",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fetchStrategyApr",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "i_vault", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "s_keepers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "s_latestSnapshot",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "s_prevSnapshot",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setKeeper",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(functionFragment: "snapshot", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "MIN_SNAPSHOT_INTERVAL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fetchLiveApr",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fetchStrategyApr",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "i_vault", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "s_keepers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "s_latestSnapshot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "s_prevSnapshot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setKeeper", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "snapshot", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace KeeperUpdatedEvent {
  export type InputTuple = [keeper: AddressLike, active: boolean];
  export type OutputTuple = [keeper: string, active: boolean];
  export interface OutputObject {
    keeper: string;
    active: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferStartedEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SnapshotRecordedEvent {
  export type InputTuple = [rate: BigNumberish, timestamp: BigNumberish];
  export type OutputTuple = [rate: bigint, timestamp: bigint];
  export interface OutputObject {
    rate: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ERC4626AprProvider extends BaseContract {
  connect(runner?: ContractRunner | null): ERC4626AprProvider;
  waitForDeployment(): Promise<this>;

  interface: ERC4626AprProviderInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MIN_SNAPSHOT_INTERVAL: TypedContractMethod<[], [bigint], "view">;

  acceptOwnership: TypedContractMethod<[], [void], "nonpayable">;

  fetchLiveApr: TypedContractMethod<[], [bigint], "view">;

  fetchStrategyApr: TypedContractMethod<[], [bigint], "view">;

  i_vault: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pendingOwner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  s_keepers: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  s_latestSnapshot: TypedContractMethod<
    [],
    [[bigint, bigint] & { rate: bigint; timestamp: bigint }],
    "view"
  >;

  s_prevSnapshot: TypedContractMethod<
    [],
    [[bigint, bigint] & { rate: bigint; timestamp: bigint }],
    "view"
  >;

  setKeeper: TypedContractMethod<
    [keeper: AddressLike, active: boolean],
    [void],
    "nonpayable"
  >;

  snapshot: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MIN_SNAPSHOT_INTERVAL"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "acceptOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "fetchLiveApr"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "fetchStrategyApr"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "i_vault"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pendingOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "s_keepers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "s_latestSnapshot"
  ): TypedContractMethod<
    [],
    [[bigint, bigint] & { rate: bigint; timestamp: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "s_prevSnapshot"
  ): TypedContractMethod<
    [],
    [[bigint, bigint] & { rate: bigint; timestamp: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "setKeeper"
  ): TypedContractMethod<
    [keeper: AddressLike, active: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "snapshot"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "KeeperUpdated"
  ): TypedContractEvent<
    KeeperUpdatedEvent.InputTuple,
    KeeperUpdatedEvent.OutputTuple,
    KeeperUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferStarted"
  ): TypedContractEvent<
    OwnershipTransferStartedEvent.InputTuple,
    OwnershipTransferStartedEvent.OutputTuple,
    OwnershipTransferStartedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "SnapshotRecorded"
  ): TypedContractEvent<
    SnapshotRecordedEvent.InputTuple,
    SnapshotRecordedEvent.OutputTuple,
    SnapshotRecordedEvent.OutputObject
  >;

  filters: {
    "KeeperUpdated(address,bool)": TypedContractEvent<
      KeeperUpdatedEvent.InputTuple,
      KeeperUpdatedEvent.OutputTuple,
      KeeperUpdatedEvent.OutputObject
    >;
    KeeperUpdated: TypedContractEvent<
      KeeperUpdatedEvent.InputTuple,
      KeeperUpdatedEvent.OutputTuple,
      KeeperUpdatedEvent.OutputObject
    >;

    "OwnershipTransferStarted(address,address)": TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;
    OwnershipTransferStarted: TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "SnapshotRecorded(uint256,uint256)": TypedContractEvent<
      SnapshotRecordedEvent.InputTuple,
      SnapshotRecordedEvent.OutputTuple,
      SnapshotRecordedEvent.OutputObject
    >;
    SnapshotRecorded: TypedContractEvent<
      SnapshotRecordedEvent.InputTuple,
      SnapshotRecordedEvent.OutputTuple,
      SnapshotRecordedEvent.OutputObject
    >;
  };
}
