/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as susDaiAprPairProviderSol from "./SUSDaiAprPairProvider.sol";
export type { susDaiAprPairProviderSol };
