/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as aaveAprProviderSol from "./AaveAprProvider.sol";
export type { aaveAprProviderSol };
export type { SUSDaiAprProvider } from "./SUSDaiAprProvider";
