/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as aaveAprProviderSol from "./AaveAprProvider.sol";
export type { aaveAprProviderSol };
import type * as susDaiAprPairProviderSol from "./SUSDaiAprPairProvider.sol";
export type { susDaiAprPairProviderSol };
export type { ERC4626AprProvider } from "./ERC4626AprProvider";
