/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export interface SUSDaiCooldownRequestImplInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "baseAsset"
      | "finalizeCooldown"
      | "i_sUSDai"
      | "i_unstakeCooldown"
      | "i_usdai"
      | "initiateCooldown"
      | "isCooldownComplete"
      | "s_cooldownToRedemption"
      | "s_nextCooldownId"
      | "yieldToken"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "baseAsset", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "finalizeCooldown",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "i_sUSDai", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "i_unstakeCooldown",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "i_usdai", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "initiateCooldown",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isCooldownComplete",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "s_cooldownToRedemption",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "s_nextCooldownId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "yieldToken",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "baseAsset", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "finalizeCooldown",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "i_sUSDai", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "i_unstakeCooldown",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "i_usdai", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initiateCooldown",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isCooldownComplete",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "s_cooldownToRedemption",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "s_nextCooldownId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "yieldToken", data: BytesLike): Result;
}

export interface SUSDaiCooldownRequestImpl extends BaseContract {
  connect(runner?: ContractRunner | null): SUSDaiCooldownRequestImpl;
  waitForDeployment(): Promise<this>;

  interface: SUSDaiCooldownRequestImplInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  baseAsset: TypedContractMethod<[], [string], "view">;

  finalizeCooldown: TypedContractMethod<
    [cooldownId: BigNumberish, receiver: AddressLike],
    [bigint],
    "nonpayable"
  >;

  i_sUSDai: TypedContractMethod<[], [string], "view">;

  i_unstakeCooldown: TypedContractMethod<[], [string], "view">;

  i_usdai: TypedContractMethod<[], [string], "view">;

  initiateCooldown: TypedContractMethod<
    [shares: BigNumberish],
    [[bigint, bigint] & { cooldownId: bigint; cooldownDuration: bigint }],
    "nonpayable"
  >;

  isCooldownComplete: TypedContractMethod<
    [cooldownId: BigNumberish],
    [boolean],
    "view"
  >;

  s_cooldownToRedemption: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  s_nextCooldownId: TypedContractMethod<[], [bigint], "view">;

  yieldToken: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "baseAsset"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "finalizeCooldown"
  ): TypedContractMethod<
    [cooldownId: BigNumberish, receiver: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "i_sUSDai"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "i_unstakeCooldown"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "i_usdai"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "initiateCooldown"
  ): TypedContractMethod<
    [shares: BigNumberish],
    [[bigint, bigint] & { cooldownId: bigint; cooldownDuration: bigint }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isCooldownComplete"
  ): TypedContractMethod<[cooldownId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "s_cooldownToRedemption"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "s_nextCooldownId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "yieldToken"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
