/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as primeCdoSol from "./PrimeCDO.sol";
export { Accounting__factory } from "./Accounting__factory";
export { TrancheVault__factory } from "./TrancheVault__factory";
