/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPrimeCDO,
  IPrimeCDOInterface,
} from "../../../contracts/interfaces/IPrimeCDO";

const _abi = [
  {
    inputs: [],
    name: "accounting",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "cooldownId",
        type: "uint256",
      },
    ],
    name: "claimSharesWithdraw",
    outputs: [
      {
        internalType: "uint256",
        name: "amountOut",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "cooldownId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "cooldownHandler",
        type: "address",
      },
    ],
    name: "claimWithdraw",
    outputs: [
      {
        internalType: "uint256",
        name: "amountOut",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "enum TrancheId",
        name: "tranche",
        type: "uint8",
      },
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "deposit",
    outputs: [
      {
        internalType: "uint256",
        name: "baseAmount",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "baseToken",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "baseAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "wethAmount",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "depositor",
        type: "address",
      },
    ],
    name: "depositJunior",
    outputs: [
      {
        internalType: "uint256",
        name: "totalBaseValue",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "maxBaseToRecall",
        type: "uint256",
      },
    ],
    name: "rebalanceBuyWETH",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "rebalanceSellWETH",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "enum TrancheId",
        name: "tranche",
        type: "uint8",
      },
      {
        internalType: "uint256",
        name: "baseAmount",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "beneficiary",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "vaultShares",
        type: "uint256",
      },
    ],
    name: "requestWithdraw",
    outputs: [
      {
        components: [
          {
            internalType: "bool",
            name: "isInstant",
            type: "bool",
          },
          {
            internalType: "uint256",
            name: "amountOut",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "cooldownId",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "cooldownHandler",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "unlockTime",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "feeAmount",
            type: "uint256",
          },
          {
            internalType: "enum CooldownType",
            name: "appliedCooldownType",
            type: "uint8",
          },
          {
            internalType: "uint256",
            name: "wethAmount",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "wethCooldownId",
            type: "uint256",
          },
        ],
        internalType: "struct CDOWithdrawResult",
        name: "result",
        type: "tuple",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "strategy",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "baseAmount",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "beneficiary",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "vaultShares",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "totalJuniorShares",
        type: "uint256",
      },
    ],
    name: "withdrawJunior",
    outputs: [
      {
        components: [
          {
            internalType: "bool",
            name: "isInstant",
            type: "bool",
          },
          {
            internalType: "uint256",
            name: "amountOut",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "cooldownId",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "cooldownHandler",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "unlockTime",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "feeAmount",
            type: "uint256",
          },
          {
            internalType: "enum CooldownType",
            name: "appliedCooldownType",
            type: "uint8",
          },
          {
            internalType: "uint256",
            name: "wethAmount",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "wethCooldownId",
            type: "uint256",
          },
        ],
        internalType: "struct CDOWithdrawResult",
        name: "result",
        type: "tuple",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IPrimeCDO__factory {
  static readonly abi = _abi;
  static createInterface(): IPrimeCDOInterface {
    return new Interface(_abi) as IPrimeCDOInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IPrimeCDO {
    return new Contract(address, _abi, runner) as unknown as IPrimeCDO;
  }
}
