/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface AprPairFeedInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptOwnership"
      | "clearManualOverride"
      | "getAprPair"
      | "i_aaveProvider"
      | "i_susdaiProvider"
      | "owner"
      | "pendingOwner"
      | "renounceOwnership"
      | "s_aprBase"
      | "s_aprTarget"
      | "s_lastUpdated"
      | "s_manualAprBase"
      | "s_manualAprTarget"
      | "s_manualOverride"
      | "s_staleAfter"
      | "setManualApr"
      | "setStaleAfter"
      | "transferOwnership"
      | "updateRoundData"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AprUpdated"
      | "ManualOverrideCleared"
      | "ManualOverrideSet"
      | "OwnershipTransferStarted"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "clearManualOverride",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAprPair",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "i_aaveProvider",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "i_susdaiProvider",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "s_aprBase", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "s_aprTarget",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "s_lastUpdated",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "s_manualAprBase",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "s_manualAprTarget",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "s_manualOverride",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "s_staleAfter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setManualApr",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setStaleAfter",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateRoundData",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "clearManualOverride",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAprPair", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "i_aaveProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "i_susdaiProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "s_aprBase", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "s_aprTarget",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "s_lastUpdated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "s_manualAprBase",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "s_manualAprTarget",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "s_manualOverride",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "s_staleAfter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setManualApr",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setStaleAfter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateRoundData",
    data: BytesLike
  ): Result;
}

export namespace AprUpdatedEvent {
  export type InputTuple = [
    aprTarget: BigNumberish,
    aprBase: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    aprTarget: bigint,
    aprBase: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    aprTarget: bigint;
    aprBase: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ManualOverrideClearedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ManualOverrideSetEvent {
  export type InputTuple = [aprTarget: BigNumberish, aprBase: BigNumberish];
  export type OutputTuple = [aprTarget: bigint, aprBase: bigint];
  export interface OutputObject {
    aprTarget: bigint;
    aprBase: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferStartedEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AprPairFeed extends BaseContract {
  connect(runner?: ContractRunner | null): AprPairFeed;
  waitForDeployment(): Promise<this>;

  interface: AprPairFeedInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptOwnership: TypedContractMethod<[], [void], "nonpayable">;

  clearManualOverride: TypedContractMethod<[], [void], "nonpayable">;

  getAprPair: TypedContractMethod<
    [],
    [[bigint, bigint] & { aprTarget: bigint; aprBase: bigint }],
    "view"
  >;

  i_aaveProvider: TypedContractMethod<[], [string], "view">;

  i_susdaiProvider: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pendingOwner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  s_aprBase: TypedContractMethod<[], [bigint], "view">;

  s_aprTarget: TypedContractMethod<[], [bigint], "view">;

  s_lastUpdated: TypedContractMethod<[], [bigint], "view">;

  s_manualAprBase: TypedContractMethod<[], [bigint], "view">;

  s_manualAprTarget: TypedContractMethod<[], [bigint], "view">;

  s_manualOverride: TypedContractMethod<[], [boolean], "view">;

  s_staleAfter: TypedContractMethod<[], [bigint], "view">;

  setManualApr: TypedContractMethod<
    [aprTarget_: BigNumberish, aprBase_: BigNumberish],
    [void],
    "nonpayable"
  >;

  setStaleAfter: TypedContractMethod<
    [staleAfter_: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateRoundData: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "clearManualOverride"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAprPair"
  ): TypedContractMethod<
    [],
    [[bigint, bigint] & { aprTarget: bigint; aprBase: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "i_aaveProvider"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "i_susdaiProvider"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pendingOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "s_aprBase"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "s_aprTarget"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "s_lastUpdated"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "s_manualAprBase"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "s_manualAprTarget"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "s_manualOverride"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "s_staleAfter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setManualApr"
  ): TypedContractMethod<
    [aprTarget_: BigNumberish, aprBase_: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setStaleAfter"
  ): TypedContractMethod<[staleAfter_: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateRoundData"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "AprUpdated"
  ): TypedContractEvent<
    AprUpdatedEvent.InputTuple,
    AprUpdatedEvent.OutputTuple,
    AprUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ManualOverrideCleared"
  ): TypedContractEvent<
    ManualOverrideClearedEvent.InputTuple,
    ManualOverrideClearedEvent.OutputTuple,
    ManualOverrideClearedEvent.OutputObject
  >;
  getEvent(
    key: "ManualOverrideSet"
  ): TypedContractEvent<
    ManualOverrideSetEvent.InputTuple,
    ManualOverrideSetEvent.OutputTuple,
    ManualOverrideSetEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferStarted"
  ): TypedContractEvent<
    OwnershipTransferStartedEvent.InputTuple,
    OwnershipTransferStartedEvent.OutputTuple,
    OwnershipTransferStartedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "AprUpdated(uint256,uint256,uint256)": TypedContractEvent<
      AprUpdatedEvent.InputTuple,
      AprUpdatedEvent.OutputTuple,
      AprUpdatedEvent.OutputObject
    >;
    AprUpdated: TypedContractEvent<
      AprUpdatedEvent.InputTuple,
      AprUpdatedEvent.OutputTuple,
      AprUpdatedEvent.OutputObject
    >;

    "ManualOverrideCleared()": TypedContractEvent<
      ManualOverrideClearedEvent.InputTuple,
      ManualOverrideClearedEvent.OutputTuple,
      ManualOverrideClearedEvent.OutputObject
    >;
    ManualOverrideCleared: TypedContractEvent<
      ManualOverrideClearedEvent.InputTuple,
      ManualOverrideClearedEvent.OutputTuple,
      ManualOverrideClearedEvent.OutputObject
    >;

    "ManualOverrideSet(uint256,uint256)": TypedContractEvent<
      ManualOverrideSetEvent.InputTuple,
      ManualOverrideSetEvent.OutputTuple,
      ManualOverrideSetEvent.OutputObject
    >;
    ManualOverrideSet: TypedContractEvent<
      ManualOverrideSetEvent.InputTuple,
      ManualOverrideSetEvent.OutputTuple,
      ManualOverrideSetEvent.OutputObject
    >;

    "OwnershipTransferStarted(address,address)": TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;
    OwnershipTransferStarted: TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
