/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "AccessControl",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AccessControl__factory>;
    getContractFactory(
      name: "IAccessControl",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAccessControl__factory>;
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "Ownable2Step",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable2Step__factory>;
    getContractFactory(
      name: "IERC1155Errors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1155Errors__factory>;
    getContractFactory(
      name: "IERC20Errors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Errors__factory>;
    getContractFactory(
      name: "IERC721Errors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Errors__factory>;
    getContractFactory(
      name: "IERC1363",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1363__factory>;
    getContractFactory(
      name: "IERC4626",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC4626__factory>;
    getContractFactory(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20__factory>;
    getContractFactory(
      name: "ERC4626",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC4626__factory>;
    getContractFactory(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Metadata__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "SafeERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SafeERC20__factory>;
    getContractFactory(
      name: "Address",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Address__factory>;
    getContractFactory(
      name: "Errors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Errors__factory>;
    getContractFactory(
      name: "ERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC165__factory>;
    getContractFactory(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165__factory>;
    getContractFactory(
      name: "SafeCast",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SafeCast__factory>;
    getContractFactory(
      name: "Pausable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Pausable__factory>;
    getContractFactory(
      name: "ERC20Cooldown",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20Cooldown__factory>;
    getContractFactory(
      name: "RedemptionPolicy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.RedemptionPolicy__factory>;
    getContractFactory(
      name: "SharesCooldown",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SharesCooldown__factory>;
    getContractFactory(
      name: "UnstakeCooldown",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.UnstakeCooldown__factory>;
    getContractFactory(
      name: "Accounting",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Accounting__factory>;
    getContractFactory(
      name: "PrimeCDO",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PrimeCDO__factory>;
    getContractFactory(
      name: "TrancheVault",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TrancheVault__factory>;
    getContractFactory(
      name: "RiskParams",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.RiskParams__factory>;
    getContractFactory(
      name: "IAaveWETHAdapter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAaveWETHAdapter__factory>;
    getContractFactory(
      name: "IAccounting",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAccounting__factory>;
    getContractFactory(
      name: "IAprFeed",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAprFeed__factory>;
    getContractFactory(
      name: "IAprPairFeed",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAprPairFeed__factory>;
    getContractFactory(
      name: "IStrategyAprPairProvider",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IStrategyAprPairProvider__factory>;
    getContractFactory(
      name: "ICooldownHandler",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ICooldownHandler__factory>;
    getContractFactory(
      name: "ICooldownRequestImpl",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ICooldownRequestImpl__factory>;
    getContractFactory(
      name: "IPrimeCDO",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPrimeCDO__factory>;
    getContractFactory(
      name: "IRatioController",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IRatioController__factory>;
    getContractFactory(
      name: "IStakedUSDai",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IStakedUSDai__factory>;
    getContractFactory(
      name: "IStrategy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IStrategy__factory>;
    getContractFactory(
      name: "ISwapFacility",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ISwapFacility__factory>;
    getContractFactory(
      name: "ISwapRouter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ISwapRouter__factory>;
    getContractFactory(
      name: "IWETHPriceOracle",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IWETHPriceOracle__factory>;
    getContractFactory(
      name: "AaveWETHAdapter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AaveWETHAdapter__factory>;
    getContractFactory(
      name: "IAaveV3Pool",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAaveV3Pool__factory>;
    getContractFactory(
      name: "SwapFacility",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SwapFacility__factory>;
    getContractFactory(
      name: "AggregatorV3Interface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AggregatorV3Interface__factory>;
    getContractFactory(
      name: "WETHPriceOracle",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.WETHPriceOracle__factory>;
    getContractFactory(
      name: "FixedPointMathHarness",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FixedPointMathHarness__factory>;
    getContractFactory(
      name: "AprPairFeed",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AprPairFeed__factory>;
    getContractFactory(
      name: "IAavePool",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAavePool__factory>;
    getContractFactory(
      name: "SUSDaiAprPairProvider",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SUSDaiAprPairProvider__factory>;
    getContractFactory(
      name: "IPrimeCDOLens",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPrimeCDOLens__factory>;
    getContractFactory(
      name: "ITrancheVaultLens",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ITrancheVaultLens__factory>;
    getContractFactory(
      name: "PrimeLens",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PrimeLens__factory>;
    getContractFactory(
      name: "BaseStrategy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BaseStrategy__factory>;
    getContractFactory(
      name: "SUSDaiCooldownRequestImpl",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SUSDaiCooldownRequestImpl__factory>;
    getContractFactory(
      name: "IStakedUSDai",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IStakedUSDai__factory>;
    getContractFactory(
      name: "SUSDaiStrategy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SUSDaiStrategy__factory>;
    getContractFactory(
      name: "MockAavePool",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockAavePool__factory>;
    getContractFactory(
      name: "MockAToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockAToken__factory>;
    getContractFactory(
      name: "MockAavePoolForAdapter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockAavePoolForAdapter__factory>;
    getContractFactory(
      name: "MockAWETH",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockAWETH__factory>;
    getContractFactory(
      name: "MockWETH",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockWETH__factory>;
    getContractFactory(
      name: "MockAprFeed",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockAprFeed__factory>;
    getContractFactory(
      name: "MockChainlinkFeed",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockChainlinkFeed__factory>;
    getContractFactory(
      name: "MockERC4626",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockERC4626__factory>;
    getContractFactory(
      name: "MockStakedUSDai",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockStakedUSDai__factory>;
    getContractFactory(
      name: "MockStrategy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockStrategy__factory>;
    getContractFactory(
      name: "MockSUSDai",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockSUSDai__factory>;
    getContractFactory(
      name: "MockBaseAsset",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockBaseAsset__factory>;
    getContractFactory(
      name: "MockSwapRouter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockSwapRouter__factory>;

    getContractAt(
      name: "AccessControl",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.AccessControl>;
    getContractAt(
      name: "IAccessControl",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IAccessControl>;
    getContractAt(
      name: "Ownable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "Ownable2Step",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable2Step>;
    getContractAt(
      name: "IERC1155Errors",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1155Errors>;
    getContractAt(
      name: "IERC20Errors",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Errors>;
    getContractAt(
      name: "IERC721Errors",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Errors>;
    getContractAt(
      name: "IERC1363",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1363>;
    getContractAt(
      name: "IERC4626",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC4626>;
    getContractAt(
      name: "ERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20>;
    getContractAt(
      name: "ERC4626",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC4626>;
    getContractAt(
      name: "IERC20Metadata",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Metadata>;
    getContractAt(
      name: "IERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "SafeERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SafeERC20>;
    getContractAt(
      name: "Address",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Address>;
    getContractAt(
      name: "Errors",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Errors>;
    getContractAt(
      name: "ERC165",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC165>;
    getContractAt(
      name: "IERC165",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC165>;
    getContractAt(
      name: "SafeCast",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SafeCast>;
    getContractAt(
      name: "Pausable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Pausable>;
    getContractAt(
      name: "ERC20Cooldown",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20Cooldown>;
    getContractAt(
      name: "RedemptionPolicy",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.RedemptionPolicy>;
    getContractAt(
      name: "SharesCooldown",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SharesCooldown>;
    getContractAt(
      name: "UnstakeCooldown",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.UnstakeCooldown>;
    getContractAt(
      name: "Accounting",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Accounting>;
    getContractAt(
      name: "PrimeCDO",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PrimeCDO>;
    getContractAt(
      name: "TrancheVault",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TrancheVault>;
    getContractAt(
      name: "RiskParams",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.RiskParams>;
    getContractAt(
      name: "IAaveWETHAdapter",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IAaveWETHAdapter>;
    getContractAt(
      name: "IAccounting",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IAccounting>;
    getContractAt(
      name: "IAprFeed",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IAprFeed>;
    getContractAt(
      name: "IAprPairFeed",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IAprPairFeed>;
    getContractAt(
      name: "IStrategyAprPairProvider",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IStrategyAprPairProvider>;
    getContractAt(
      name: "ICooldownHandler",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ICooldownHandler>;
    getContractAt(
      name: "ICooldownRequestImpl",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ICooldownRequestImpl>;
    getContractAt(
      name: "IPrimeCDO",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IPrimeCDO>;
    getContractAt(
      name: "IRatioController",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IRatioController>;
    getContractAt(
      name: "IStakedUSDai",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IStakedUSDai>;
    getContractAt(
      name: "IStrategy",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IStrategy>;
    getContractAt(
      name: "ISwapFacility",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ISwapFacility>;
    getContractAt(
      name: "ISwapRouter",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ISwapRouter>;
    getContractAt(
      name: "IWETHPriceOracle",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IWETHPriceOracle>;
    getContractAt(
      name: "AaveWETHAdapter",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.AaveWETHAdapter>;
    getContractAt(
      name: "IAaveV3Pool",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IAaveV3Pool>;
    getContractAt(
      name: "SwapFacility",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SwapFacility>;
    getContractAt(
      name: "AggregatorV3Interface",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.AggregatorV3Interface>;
    getContractAt(
      name: "WETHPriceOracle",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.WETHPriceOracle>;
    getContractAt(
      name: "FixedPointMathHarness",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.FixedPointMathHarness>;
    getContractAt(
      name: "AprPairFeed",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.AprPairFeed>;
    getContractAt(
      name: "IAavePool",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IAavePool>;
    getContractAt(
      name: "SUSDaiAprPairProvider",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SUSDaiAprPairProvider>;
    getContractAt(
      name: "IPrimeCDOLens",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IPrimeCDOLens>;
    getContractAt(
      name: "ITrancheVaultLens",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ITrancheVaultLens>;
    getContractAt(
      name: "PrimeLens",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PrimeLens>;
    getContractAt(
      name: "BaseStrategy",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.BaseStrategy>;
    getContractAt(
      name: "SUSDaiCooldownRequestImpl",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SUSDaiCooldownRequestImpl>;
    getContractAt(
      name: "IStakedUSDai",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IStakedUSDai>;
    getContractAt(
      name: "SUSDaiStrategy",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SUSDaiStrategy>;
    getContractAt(
      name: "MockAavePool",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockAavePool>;
    getContractAt(
      name: "MockAToken",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockAToken>;
    getContractAt(
      name: "MockAavePoolForAdapter",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockAavePoolForAdapter>;
    getContractAt(
      name: "MockAWETH",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockAWETH>;
    getContractAt(
      name: "MockWETH",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockWETH>;
    getContractAt(
      name: "MockAprFeed",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockAprFeed>;
    getContractAt(
      name: "MockChainlinkFeed",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockChainlinkFeed>;
    getContractAt(
      name: "MockERC4626",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockERC4626>;
    getContractAt(
      name: "MockStakedUSDai",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockStakedUSDai>;
    getContractAt(
      name: "MockStrategy",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockStrategy>;
    getContractAt(
      name: "MockSUSDai",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockSUSDai>;
    getContractAt(
      name: "MockBaseAsset",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockBaseAsset>;
    getContractAt(
      name: "MockSwapRouter",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockSwapRouter>;

    deployContract(
      name: "AccessControl",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AccessControl>;
    deployContract(
      name: "IAccessControl",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAccessControl>;
    deployContract(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "Ownable2Step",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable2Step>;
    deployContract(
      name: "IERC1155Errors",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1155Errors>;
    deployContract(
      name: "IERC20Errors",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Errors>;
    deployContract(
      name: "IERC721Errors",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Errors>;
    deployContract(
      name: "IERC1363",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1363>;
    deployContract(
      name: "IERC4626",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC4626>;
    deployContract(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC20>;
    deployContract(
      name: "ERC4626",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC4626>;
    deployContract(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Metadata>;
    deployContract(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "SafeERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SafeERC20>;
    deployContract(
      name: "Address",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Address>;
    deployContract(
      name: "Errors",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Errors>;
    deployContract(
      name: "ERC165",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC165>;
    deployContract(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC165>;
    deployContract(
      name: "SafeCast",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SafeCast>;
    deployContract(
      name: "Pausable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Pausable>;
    deployContract(
      name: "ERC20Cooldown",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC20Cooldown>;
    deployContract(
      name: "RedemptionPolicy",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RedemptionPolicy>;
    deployContract(
      name: "SharesCooldown",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SharesCooldown>;
    deployContract(
      name: "UnstakeCooldown",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.UnstakeCooldown>;
    deployContract(
      name: "Accounting",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Accounting>;
    deployContract(
      name: "PrimeCDO",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrimeCDO>;
    deployContract(
      name: "TrancheVault",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TrancheVault>;
    deployContract(
      name: "RiskParams",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RiskParams>;
    deployContract(
      name: "IAaveWETHAdapter",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAaveWETHAdapter>;
    deployContract(
      name: "IAccounting",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAccounting>;
    deployContract(
      name: "IAprFeed",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAprFeed>;
    deployContract(
      name: "IAprPairFeed",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAprPairFeed>;
    deployContract(
      name: "IStrategyAprPairProvider",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IStrategyAprPairProvider>;
    deployContract(
      name: "ICooldownHandler",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ICooldownHandler>;
    deployContract(
      name: "ICooldownRequestImpl",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ICooldownRequestImpl>;
    deployContract(
      name: "IPrimeCDO",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPrimeCDO>;
    deployContract(
      name: "IRatioController",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IRatioController>;
    deployContract(
      name: "IStakedUSDai",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IStakedUSDai>;
    deployContract(
      name: "IStrategy",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IStrategy>;
    deployContract(
      name: "ISwapFacility",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISwapFacility>;
    deployContract(
      name: "ISwapRouter",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISwapRouter>;
    deployContract(
      name: "IWETHPriceOracle",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IWETHPriceOracle>;
    deployContract(
      name: "AaveWETHAdapter",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AaveWETHAdapter>;
    deployContract(
      name: "IAaveV3Pool",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAaveV3Pool>;
    deployContract(
      name: "SwapFacility",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SwapFacility>;
    deployContract(
      name: "AggregatorV3Interface",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AggregatorV3Interface>;
    deployContract(
      name: "WETHPriceOracle",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.WETHPriceOracle>;
    deployContract(
      name: "FixedPointMathHarness",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FixedPointMathHarness>;
    deployContract(
      name: "AprPairFeed",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AprPairFeed>;
    deployContract(
      name: "IAavePool",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAavePool>;
    deployContract(
      name: "SUSDaiAprPairProvider",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SUSDaiAprPairProvider>;
    deployContract(
      name: "IPrimeCDOLens",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPrimeCDOLens>;
    deployContract(
      name: "ITrancheVaultLens",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ITrancheVaultLens>;
    deployContract(
      name: "PrimeLens",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrimeLens>;
    deployContract(
      name: "BaseStrategy",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BaseStrategy>;
    deployContract(
      name: "SUSDaiCooldownRequestImpl",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SUSDaiCooldownRequestImpl>;
    deployContract(
      name: "IStakedUSDai",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IStakedUSDai>;
    deployContract(
      name: "SUSDaiStrategy",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SUSDaiStrategy>;
    deployContract(
      name: "MockAavePool",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockAavePool>;
    deployContract(
      name: "MockAToken",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockAToken>;
    deployContract(
      name: "MockAavePoolForAdapter",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockAavePoolForAdapter>;
    deployContract(
      name: "MockAWETH",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockAWETH>;
    deployContract(
      name: "MockWETH",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockWETH>;
    deployContract(
      name: "MockAprFeed",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockAprFeed>;
    deployContract(
      name: "MockChainlinkFeed",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockChainlinkFeed>;
    deployContract(
      name: "MockERC4626",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockERC4626>;
    deployContract(
      name: "MockStakedUSDai",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockStakedUSDai>;
    deployContract(
      name: "MockStrategy",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockStrategy>;
    deployContract(
      name: "MockSUSDai",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockSUSDai>;
    deployContract(
      name: "MockBaseAsset",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockBaseAsset>;
    deployContract(
      name: "MockSwapRouter",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockSwapRouter>;

    deployContract(
      name: "AccessControl",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AccessControl>;
    deployContract(
      name: "IAccessControl",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAccessControl>;
    deployContract(
      name: "Ownable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "Ownable2Step",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable2Step>;
    deployContract(
      name: "IERC1155Errors",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1155Errors>;
    deployContract(
      name: "IERC20Errors",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Errors>;
    deployContract(
      name: "IERC721Errors",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Errors>;
    deployContract(
      name: "IERC1363",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1363>;
    deployContract(
      name: "IERC4626",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC4626>;
    deployContract(
      name: "ERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC20>;
    deployContract(
      name: "ERC4626",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC4626>;
    deployContract(
      name: "IERC20Metadata",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Metadata>;
    deployContract(
      name: "IERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "SafeERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SafeERC20>;
    deployContract(
      name: "Address",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Address>;
    deployContract(
      name: "Errors",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Errors>;
    deployContract(
      name: "ERC165",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC165>;
    deployContract(
      name: "IERC165",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC165>;
    deployContract(
      name: "SafeCast",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SafeCast>;
    deployContract(
      name: "Pausable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Pausable>;
    deployContract(
      name: "ERC20Cooldown",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC20Cooldown>;
    deployContract(
      name: "RedemptionPolicy",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RedemptionPolicy>;
    deployContract(
      name: "SharesCooldown",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SharesCooldown>;
    deployContract(
      name: "UnstakeCooldown",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.UnstakeCooldown>;
    deployContract(
      name: "Accounting",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Accounting>;
    deployContract(
      name: "PrimeCDO",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrimeCDO>;
    deployContract(
      name: "TrancheVault",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TrancheVault>;
    deployContract(
      name: "RiskParams",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RiskParams>;
    deployContract(
      name: "IAaveWETHAdapter",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAaveWETHAdapter>;
    deployContract(
      name: "IAccounting",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAccounting>;
    deployContract(
      name: "IAprFeed",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAprFeed>;
    deployContract(
      name: "IAprPairFeed",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAprPairFeed>;
    deployContract(
      name: "IStrategyAprPairProvider",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IStrategyAprPairProvider>;
    deployContract(
      name: "ICooldownHandler",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ICooldownHandler>;
    deployContract(
      name: "ICooldownRequestImpl",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ICooldownRequestImpl>;
    deployContract(
      name: "IPrimeCDO",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPrimeCDO>;
    deployContract(
      name: "IRatioController",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IRatioController>;
    deployContract(
      name: "IStakedUSDai",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IStakedUSDai>;
    deployContract(
      name: "IStrategy",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IStrategy>;
    deployContract(
      name: "ISwapFacility",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISwapFacility>;
    deployContract(
      name: "ISwapRouter",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISwapRouter>;
    deployContract(
      name: "IWETHPriceOracle",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IWETHPriceOracle>;
    deployContract(
      name: "AaveWETHAdapter",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AaveWETHAdapter>;
    deployContract(
      name: "IAaveV3Pool",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAaveV3Pool>;
    deployContract(
      name: "SwapFacility",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SwapFacility>;
    deployContract(
      name: "AggregatorV3Interface",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AggregatorV3Interface>;
    deployContract(
      name: "WETHPriceOracle",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.WETHPriceOracle>;
    deployContract(
      name: "FixedPointMathHarness",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FixedPointMathHarness>;
    deployContract(
      name: "AprPairFeed",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AprPairFeed>;
    deployContract(
      name: "IAavePool",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAavePool>;
    deployContract(
      name: "SUSDaiAprPairProvider",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SUSDaiAprPairProvider>;
    deployContract(
      name: "IPrimeCDOLens",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPrimeCDOLens>;
    deployContract(
      name: "ITrancheVaultLens",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ITrancheVaultLens>;
    deployContract(
      name: "PrimeLens",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrimeLens>;
    deployContract(
      name: "BaseStrategy",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BaseStrategy>;
    deployContract(
      name: "SUSDaiCooldownRequestImpl",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SUSDaiCooldownRequestImpl>;
    deployContract(
      name: "IStakedUSDai",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IStakedUSDai>;
    deployContract(
      name: "SUSDaiStrategy",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SUSDaiStrategy>;
    deployContract(
      name: "MockAavePool",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockAavePool>;
    deployContract(
      name: "MockAToken",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockAToken>;
    deployContract(
      name: "MockAavePoolForAdapter",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockAavePoolForAdapter>;
    deployContract(
      name: "MockAWETH",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockAWETH>;
    deployContract(
      name: "MockWETH",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockWETH>;
    deployContract(
      name: "MockAprFeed",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockAprFeed>;
    deployContract(
      name: "MockChainlinkFeed",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockChainlinkFeed>;
    deployContract(
      name: "MockERC4626",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockERC4626>;
    deployContract(
      name: "MockStakedUSDai",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockStakedUSDai>;
    deployContract(
      name: "MockStrategy",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockStrategy>;
    deployContract(
      name: "MockSUSDai",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockSUSDai>;
    deployContract(
      name: "MockBaseAsset",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockBaseAsset>;
    deployContract(
      name: "MockSwapRouter",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockSwapRouter>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
