/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface AaveWETHAdapterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "currentAPR"
      | "i_aWeth"
      | "i_aavePool"
      | "i_priceOracle"
      | "i_primeCDO"
      | "i_weth"
      | "supply"
      | "totalAssets"
      | "totalAssetsUSD"
      | "withdraw"
      | "withdrawAll"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "currentAPR",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "i_aWeth", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "i_aavePool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "i_priceOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "i_primeCDO",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "i_weth", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "supply",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalAssets",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalAssetsUSD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawAll",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "currentAPR", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "i_aWeth", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "i_aavePool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "i_priceOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "i_primeCDO", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "i_weth", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "supply", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalAssets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalAssetsUSD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawAll",
    data: BytesLike
  ): Result;
}

export interface AaveWETHAdapter extends BaseContract {
  connect(runner?: ContractRunner | null): AaveWETHAdapter;
  waitForDeployment(): Promise<this>;

  interface: AaveWETHAdapterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  currentAPR: TypedContractMethod<[], [bigint], "view">;

  i_aWeth: TypedContractMethod<[], [string], "view">;

  i_aavePool: TypedContractMethod<[], [string], "view">;

  i_priceOracle: TypedContractMethod<[], [string], "view">;

  i_primeCDO: TypedContractMethod<[], [string], "view">;

  i_weth: TypedContractMethod<[], [string], "view">;

  supply: TypedContractMethod<
    [wethAmount: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  totalAssets: TypedContractMethod<[], [bigint], "view">;

  totalAssetsUSD: TypedContractMethod<[], [bigint], "view">;

  withdraw: TypedContractMethod<
    [wethAmount: BigNumberish, to: AddressLike],
    [bigint],
    "nonpayable"
  >;

  withdrawAll: TypedContractMethod<[to: AddressLike], [bigint], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "currentAPR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "i_aWeth"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "i_aavePool"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "i_priceOracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "i_primeCDO"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "i_weth"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "supply"
  ): TypedContractMethod<[wethAmount: BigNumberish], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "totalAssets"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalAssetsUSD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<
    [wethAmount: BigNumberish, to: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawAll"
  ): TypedContractMethod<[to: AddressLike], [bigint], "nonpayable">;

  filters: {};
}
